version: '3'
services:
  app:
    build:
      dockerfile: ./docker/app/Dockerfile
    restart: always
    env_file:
    - path: ./.env
      required: true # default
    - path: ./local.env
      required: false
    depends_on:
      - db
  db:
    image: postgres:16.1
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: x2tg
      POSTGRES_DB: x2tg
      POSTGRES_PASSWORD: 123456